#!/usr/bin/env bash
set -e

declare -A sets=(
  ["Unlimited Edition"]="2U"
  ["Arabian Nights"]="AN"
  ["Antiquities"]="AQ"
  ["Legends"]="LE"
  ["The Dark"]="DK"
  ["Fallen Empires"]="FE"
  ["Homelands"]="HM"
  ["Ice Age"]="IA"
  ["Alliances"]="AL"
  ["Coldsnap"]="CSP"
  ["Mirage"]="MI"
  ["Visions"]="VI"
  ["Weatherlight"]="WL"
  ["Tempest"]="TE"
  ["Stronghold"]="ST"
  ["Exodus"]="EX"
  ["Urza's Saga"]="UZ"
  ["Urza's Legacy"]="GU"
  ["Urza's Destiny"]="CG"
  ["Mercadian Masques"]="MM"
  ["Nemesis"]="NE"
  ["Prophecy"]="PR"
  ["Invasion"]="IN"
  ["Planeshift"]="PS"
  ["Apocalypse"]="AP"
  ["Odyssey"]="OD"
  ["Torment"]="TOR"
  ["Judgment"]="JUD"
  ["Onslaught"]="ONS"
  ["Legions"]="LGN"
  ["Scourge"]="SCG"
  ["Mirrodin"]="MRD"
  ["Darksteel"]="DST"
  ["Fifth Dawn"]="5DN"
  ["Champions of Kamigawa"]="CHK"
  ["Betrayers of Kamigawa"]="BOK"
  ["Saviors of Kamigawa"]="SOK"
  ["Ravnica: City of Guilds"]="RAV"
  ["Guildpact"]="GPT"
  ["Dissension"]="DIS"
  ["Time Spiral"]="TSP"
  ["Planar Chaos"]="PLC"
  ["Future Sight"]="FUT"
  ["Lorwyn"]="LRW"
  ["Morningtide"]="MOR"
  ["Shadowmoor"]="SHM"
  ["Eventide"]="EVE"
  ["Shards of Alara"]="ALA"
  ["Conflux"]="CON"
  ["Alara Reborn"]="ARB"
  ["Magic 2010"]="M10"
  ["Zendikar"]="ZEN"
  ["Worldwake"]="WWK"
  ["Rise of the Eldrazi"]="ROE"
  ["Scars of Mirrodin"]="SOM"
  ["Mirrodin Besieged"]="MBS"
  ["New Phyrexia"]="NPH"
  ["Innistrad"]="ISD"
  ["Dark Ascension"]="DKA"
  ["Avacyn Restored"]="AVR"
  ["Return to Ravnica"]="RTR"
  ["Gatecrash"]="GTC"
  ["Dragon's Maze"]="DGM"
  ["Magic 2014"]="M14"
  ["Theros"]="THS"
  ["Commander 2013"]="C13"
  ["Born of the Gods"]="BNG"
  ["Journey into Nyx"]="JOU"
  ["Khans of Tarkir"]="KTK"
  ["Fate Reforged"]="FRF"
  ["Dragons of Tarkir"]="DTK"
  ["Magic Origins"]="ORI"
  ["Battle for Zendikar"]="BFZ"
)

uriencode() {
  s="${1//' '/'%20'}"
  s="${s//'"'/'%22'}"
  s="${s//'#'/'%23'}"
  s="${s//'$'/'%24'}"
  s="${s//'&'/'%26'}"
  s="${s//'+'/'%2B'}"
  s="${s//','/'%2C'}"
  s="${s//'/'/'%2F'}"
  s="${s//':'/'%3A'}"
  s="${s//';'/'%3B'}"
  s="${s//'='/'%3D'}"
  s="${s//'?'/'%3F'}"
  s="${s//'@'/'%40'}"
  s="${s//'['/'%5B'}"
  s="${s//']'/'%5D'}"
  printf %s "$s"
}

escape() {
  s="${1//'&'/&amp;}"
  s="${s//'"'/&quot;}"
  s="${s//'<'/&lt;}"
  s="${s//'>'/&gt;}"
  printf %s "$s"
}

pattern='^- \[\([ x]\)\] \(.*\) (\(.*\))$'

cat <<HEADER
<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <title>Cube</title>
  <style>
    body {
      margin: 0;
      background: #eed;
      padding: 0 32px 32px 287px;
      font-family: Palatino, serif;
    }
    h3 {
      margin: 0;
      padding: 1em 0 0.75em;
      font-size: 1.25em;
    }
    ul {
      margin: -3px;
      padding: 0;
      list-style: none;
    }
    li {
      float: left;
      margin: 3px;
    }
    li[data-checked="false"] {
      opacity: 0.5;
    }
    img {
      display: block;
      width: 92px;
      height: 128px;
      border-radius: 4px;
      box-shadow: 0 1px 5px rgba(0, 0, 0, 0.4);
    }
    #large-card {
      position: fixed;
      left: 32px;
      top: 57px;
      width: 223px;
      height: 310px;
      border-radius: 10px;
    }
  </style>
</head>
<body>
  <img id="large-card" alt="placeholder" src="http://gatherer.wizards.com/Handlers/Image.ashx?name=xxx&type=card">
HEADER

in_block=false
while read line ; do
  if [[ "$line" == \#* ]] ; then
    heading="${line/'### '/}"
    printf '  <h3 id="%s">%s</h3>\n' "$(tr [:upper:] [:lower:] <<<"$heading")" "$(escape "$heading")"
  elif [[ "$line" == -* ]] ; then
    box_value="$(sed "s:$pattern:\1:" <<<"$line")"
    card_name="$(sed "s:$pattern:\2:" <<<"$line")"
    expansion="$(sed "s:$pattern:\3:" <<<"$line")"
    printf '    <li data-checked="%s"><a href="%s"><img src="%s" alt="%s"></a></li>\n' \
      "$([[ "$box_value" == x ]] && echo true || echo false)" \
      "$(escape "http://gatherer.wizards.com/Pages/Card/Details.aspx?name=$(uriencode "$card_name")")" \
      "$(escape "http://gatherer.wizards.com/Handlers/Image.ashx?name=$(uriencode "$card_name")&set=${sets["$expansion"]}&type=card")" \
      "$(escape "$card_name")"
  elif [[ "$in_block" == false ]] ; then
    in_block=true
    printf '  <ul>\n'
  elif [[ "$in_block" == true ]] ; then
    in_block=false
    printf '  </ul>\n  <div style="clear:left"></div>\n'
  fi
done <"$1"

cat <<FOOTER
  <script>
    (function() {
      'use strict';

      var repeat = function(n, s) { return new Array(n + 1).join(s); };
      var counts = [];
      var output = '\n';
      var nodeList = document.getElementsByTagName('h3');
      for (var idx = 0; idx < nodeList.length; idx += 1) {
        var left = nodeList[idx].textContent + ' ';
        var right = ' ' + (counts[counts.length] = nodeList[idx].nextElementSibling.getElementsByTagName('li').length);
        output += left + repeat(20 - left.length - right.length, '.') + right + '\n';
      }
      var total = String(counts.reduce(function(a, b) { return a + b; }, 0));
      output += repeat(20, '=') + '\n';
      output += repeat(20 - total.length, ' ') + total + '\n';
      output += '\n';
      console.log(output);

      var largeCard = document.getElementById('large-card');
      document.body.addEventListener('mouseover', function(event) {
        if (event.target.tagName === 'IMG') {
          largeCard.alt = event.target.alt;
          largeCard.src = event.target.src;
        }
      }, false);
    }());
  </script>
</body>
</html>
FOOTER
